name = "NQCRegistry"
uuid = "8e22b3bd-71eb-4318-acc2-26d9931dd421"
repo = "https://github.com/NQCD/NQCRegistry"

[packages]
07253886-9aba-4a5d-b3d5-29b8b100a664 = { name = "NNInterfaces", path = "N/NNInterfaces" }
0e168e98-d76b-4d03-b07e-2b13986b2fd0 = { name = "FrictionProviders", path = "F/FrictionProviders" }
1c79c530-3a9d-43cd-822f-bba4c4e182d2 = { name = "FortranNOAu111", path = "F/FortranNOAu111" }
36248dfb-79eb-4f4d-ab9c-e29ea5f33e14 = { name = "NQCDynamics", path = "N/NQCDynamics" }
56146587-2a70-4d59-809c-88d5ba27a8d3 = { name = "CubeLDFAModel", path = "C/CubeLDFAModel" }
657014a1-bd25-4aa2-92cb-cbcede0310ad = { name = "NQCDistributions", path = "N/NQCDistributions" }
78c76ebc-5665-4934-b512-82d81b5cbfb7 = { name = "NQCBase", path = "N/NQCBase" }
81cd853e-d334-476c-b156-f95acc8a32dc = { name = "RingPolymerArrays", path = "R/RingPolymerArrays" }
99977979-b085-4ef1-bf27-0f203366d47f = { name = "NOAu111", path = "N/NOAu111" }
a822e7dc-5958-54de-9eb2-fa386864eb49 = { name = "H2AgModel_jll", path = "H/H2AgModel_jll" }
afbd8296-3698-5225-a961-b133c2a0387f = { name = "libsurfgen_jll", path = "L/libsurfgen_jll" }
c814dc9f-a51f-4eaf-877f-82eda4edad48 = { name = "NQCModels", path = "N/NQCModels" }
e503717d-a42a-4366-b4a7-cbf3fd5bcc4b = { name = "EANNCOAuModel", path = "E/EANNCOAuModel" }
